from service.elevenlabs_api import parse_conversation

conv = [
    {
        "role": "user",
        "message": "Hello there! Hello!",
        "tool_calls": [...],
        "tool_results": [...],
        "feedback": None,
        "llm_override": None,
        "time_in_call_secs": 2,
        "conversation_turn_metrics": None,
        "rag_retrieval_info": None,
    },
    {
        "role": "agent",
        "message": "...",
        "tool_calls": [...],
        "tool_results": [...],
        "feedback": None,
        "llm_override": None,
        "time_in_call_secs": 12,
        "conversation_turn_metrics": {...},
        "rag_retrieval_info": None,
    },
    {
        "role": "user",
        "message": "Hello",
        "tool_calls": [...],
        "tool_results": [...],
        "feedback": None,
        "llm_override": None,
        "time_in_call_secs": 2,
        "conversation_turn_metrics": None,
        "rag_retrieval_info": None,
    },
    {
        "role": "agent",
        "message": "...",
        "tool_calls": [...],
        "tool_results": [...],
        "feedback": None,
        "llm_override": None,
        "time_in_call_secs": 15,
        "conversation_turn_metrics": None,
        "rag_retrieval_info": None,
    },
    {
        "role": "user",
        "message": "Hello Hello What are you doing?",
        "tool_calls": [...],
        "tool_results": [...],
        "feedback": None,
        "llm_override": None,
        "time_in_call_secs": 2,
        "conversation_turn_metrics": None,
        "rag_retrieval_info": None,
    },
    {
        "role": "agent",
        "message": "Hello!...",
        "tool_calls": [...],
        "tool_results": [...],
        "feedback": None,
        "llm_override": None,
        "time_in_call_secs": 18,
        "conversation_turn_metrics": {...},
        "rag_retrieval_info": None,
    },
]

print(parse_conversation(conv))
